# Generated by Django 2.2.1 on 2019-05-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract_base_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='condo_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='f_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='has_access_to_facility',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='l_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unit_floor',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unit_unit',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
