version: '3.7'
services:
  web:
    image: python
    container_name: django_CustomUser_testing
    build: .
    volumes:
      - .:/home
    expose:
      - "5000"
      - "8000"
    ports:
      - "5000:5000"
      - "8000:8000"
    environment:
      POSTGRES_PASSWORD: test
      LC_ALL: "C.UTF-8"
      LANG: "C.UTF-8"
      DEBUG: 'true'
    